### ISSUE TITLE
Add missing null data type

### ISSUE THREAD

**Issue by amerikan** [GeekwiseAcademy/virtual-javascript#8]
**Describe the bug**

**To Reproduce**
1. Go to https://geekwiseacademy.github.io/virtual-javascript/two.html

**Expected behavior**

1. `null` should be listed as a **primitive** type. 
2. `typeof` should not be part of the list, as it's just a operator, needs to be un-indented one level
3. Consider adding **Data Structures**: **array** and **objects**. I usually tell the students that we can use primitives to create larger custom structures and give a few examples using them, but I let them know we'll go in more depth in later days.
4. Consider mentioning that they're **dynamic** and **weakly** typed and what that means in Variable section

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ayojackay** [comment]
@amerikan Yeah, I noticed that last Wednesday when I was going over `primitive` data types that `null` isn't included, and while I went ahead and explained it because I know it's one of the types, it's not helpful when the class would like to go back to re-review, and it isn't there 😅 
I appreciate it! I'll try to get this resolved very soon!
